apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-home
  namespace: tw1-13
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 500Gi