# nbgrader-exchange-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbgrader-exchange
spec:
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
