kind: Route
apiVersion: route.openshift.io/v1
metadata:
  # had to rename from 'notebooks' (default)
  # mistakenly configuring openid with 'notebook' (singular)
  name: notebook
spec:
  to:
    kind: Service
    name: proxy-public
    weight: 100
  port:
    targetPort: 8000
  tls:
    termination: edge
  wildcardPolicy: None
